const { Bot, InlineKeyboard } = require('grammy');
const config = require('../config');
const { getQuote, SOL_MINT, keypairFromSecret, getSolBalance, executeSwap } = require('../services/solana');
const { getSettings, saveSettings } = require('../services/settings');
const { DexWatcher } = require('../services/dexwatcher');
const { openPosition, getPositions, savePositions, replacePositions, closePosition, refreshPositionsCached } = require('../services/paper');
const { startHealthServer } = require('../health-server');
startHealthServer();
const bot = new Bot(config.token);
const isAdmin = (ctx) => String(ctx.from?.id) === String(config.adminId);
const settings = () => getSettings(config.adminId, config.encryptionKey);
const save = (s) => saveSettings(config.adminId, s, config.encryptionKey);
const yesNo = (x) => x ? '🟢' : '🔴';
const short = (v) => v ? `${String(v).slice(0, 6)}…${String(v).slice(-5)}` : 'غير متاح';
const money = (x) => Number(x || 0).toLocaleString('en-US');
const safeAnswer = async (ctx, text) => { try { await ctx.answerCallbackQuery(text); } catch (error) { if (!/query is too old|query ID is invalid|query is too old/i.test(error.description || error.message || '')) throw error; } };
const mainKeyboard = (s) => new InlineKeyboard().text('▶️ تشغيل', 'watch:on').text('⏹ إيقاف', 'watch:off').row().text('⚙️ الإعدادات', 'settings').row().text('📊 لوحة القنص — DEX', 'dashboard').row().text('💼 المحفظة', 'wallet').text('🪙 العملات غير المباعة', 'unsold').row().text(s.paperTradingEnabled ? '🧪 تداول وهمي (Paper)' : '💰 تداول حقيقي (Live)', 'mode:toggle').row().text('🔄 إعادة ضبط', 'reset:ask');
const filtersKeyboard = (s) => new InlineKeyboard().text('📊 فلاتر DexPaprika', 'filters:dex').row().text(`🛡️ فلاتر GoPlus ${yesNo(s.goplus.enabled)}`, 'filters:goplus').row().text(`🛡️ فلاتر Solana Tracker ${yesNo(s.tracker.enabled)}`, 'filters:tracker').row().text('🛑 إدارة المخاطر', 'filters:risk').row().text('🔙 رجوع', 'settings');
const settingsKeyboard = (s) => new InlineKeyboard().text(`💰 حجم الصفقة: ${s.paperAllocationPct}%`, 'cfg:allocation').row().text(`🔢 عدد الصفقات: ${s.maxTradesPerDay || 'غير محدود'}`, 'cfg:trades').row().text(`🎯 جني الأرباح: +${s.paperTakeProfitFirstPct}%`, 'cfg:profit').row().text(`🛑 وقف الخسارة: -${s.paperStopLossPct}%`, 'cfg:stop').row().text(s.paperTradingEnabled ? '✅ الشراء التلقائي: مفعّل' : '⛔ الشراء التلقائي: معطّل', 'cfg:buy').row().text(s.autoSellEnabled ? '💰 البيع التلقائي: مفعّل' : '⛔ البيع التلقائي: معطّل', 'cfg:sell').row().text('⚙️ فلاتر الحماية', 'filters').row().text('🔙 رجوع للوحة', 'home');
const list = (fields, section, s) => { const k = new InlineKeyboard(); for (const [key, label, formatter] of fields) k.text(`${label}: ${formatter(s[section][key])}`, `choose:${section}:${key}`).row(); return k.text('🔙 رجوع', 'settings'); };
const dexFields = [['minAgeSec','⏱️ العمر الأدنى',(v)=>`${v}ث`],['maxAgeSec','📅 العمر الأقصى',(v)=>v?`${v}ث`:'مفتوح'],['minVolumeUsd','💵 الحجم 24س',(v)=>`$${money(v)}`],['minLiquidityUsd','💧 السيولة',(v)=>`$${money(v)}`],['minBuys24h','📈 عدد المشتريات 24س',(v)=>v],['minBuySellRatio','⚖️ نسبة الشراء/البيع',(v)=>`${v}x`],['minMarketCapUsd','🎯 القيمة السوقية الدنيا',(v)=>`$${money(v)}`],['maxMarketCapUsd','🎯 القيمة السوقية العليا',(v)=>v?`$${money(v)}`:'مفتوح'],['antiDuplicate','🔍 منع تكرار الرمز',(v)=>v?'مفعّل':'معطّل'],['allowedDexes','🏦 DEX المسموح',(v)=>({raydium:'Raydium فقط',raydium_orca:'Raydium + Orca',raydium_orca_meteora:'Raydium + Orca + Meteora',all:'كل DEX'}[v]||v)]];
const goplusFields = [['enabled','🟢/🔴 الحالة',(v)=>v?'مفعّل':'معطّل'],['maxBuyTax','💸 أقصى ضريبة شراء',(v)=>v<0?'لا حد':`${v}%`],['maxSellTax','💸 أقصى ضريبة بيع',(v)=>v<0?'لا حد':`${v}%`],['rejectHoneypot','🚫 رفض Honeypot',(v)=>v?'مفعّل':'معطّل'],['checkMintAuthority','🔓 فحص Mint Authority',(v)=>v?'مفعّل':'معطّل'],['checkFreezeAuthority','🔓 فحص Freeze Authority',(v)=>v?'مفعّل':'معطّل']];
const trackerFields = [['enabled','🟢/🔴 الحالة',(v)=>v?'مفعّل':'معطّل'],['maxRiskScore','🎯 أقصى Risk Score',(v)=>v<0?'معطّل':v],['rejectRugged','🚫 رفض Rugged',(v)=>v?'مفعّل':'معطّل'],['maxDeveloperHoldingPct','👨‍💻 أقصى حيازة المطور',(v)=>v<0?'معطّل':`${v}%`],['maxSnipersPct','🎯 أقصى نسبة Snipers',(v)=>v<0?'معطّل':`${v}%`],['maxInsidersPct','🎯 أقصى نسبة Insiders',(v)=>v<0?'معطّل':`${v}%`],['maxBundlersPct','📦 أقصى نسبة Bundlers',(v)=>v<0?'معطّل':`${v}%`],['maxTop10Pct','🐋 أقصى نسبة Top 10',(v)=>v<0?'معطّل':`${v}%`],['minHolders','👥 أقل عدد حائزين',(v)=>v<0?'معطّل':v],['maxDeveloperTokens','📊 أقصى عدد عملات المطور',(v)=>v<0?'معطّل':v]];
const riskFields = [['stopLossPct','🛑 وقف الخسارة',(v)=>`-${v}%`],['capitalProtection','🛡️ حماية رأس المال',(v)=>v==='off'?'معطّل':v],['timedSellMin','⏰ البيع الزمني',(v)=>v?`${v}د`:'معطّل'],['emergencyBreaker','🚨 قاطع الطوارئ',(v)=>v?'مفعّل':'معطّل'],['dailyLossPct','📉 حد الخسارة اليومي',(v)=>v?`${v}%`:'معطّل']];
const screen = (section, s) => list(section === 'dex' ? dexFields : section === 'goplus' ? goplusFields : section === 'tracker' ? trackerFields : riskFields, section, s);
const choices = { 'dex:minAgeSec':[[0,'لا يهم'],[30,'30ث'],[60,'60ث'],[300,'300ث'],[900,'900ث'],[3600,'ساعة']], 'dex:maxAgeSec':[[0,'مفتوح'],[3600,'ساعة'],[21600,'6 ساعات'],[86400,'24 ساعة'],[604800,'أسبوع']], 'dex:minVolumeUsd':[[0,'لا يهم'],[100,'$100'],[500,'$500'],[1000,'$1,000'],[5000,'$5,000'],[10000,'$10,000']], 'dex:minLiquidityUsd':[[0,'لا يهم'],[200,'$200'],[500,'$500'],[1000,'$1,000'],[2000,'$2,000'],[5000,'$5,000']], 'dex:minBuys24h':[[0,'لا يهم'],[1,'1'],[3,'3'],[5,'5'],[10,'10'],[25,'25'],[50,'50']], 'dex:minMarketCapUsd':[[0,'لا يهم'],[1000,'$1,000'],[5000,'$5,000'],[10000,'$10,000'],[25000,'$25,000'],[50000,'$50,000']], 'dex:maxMarketCapUsd':[[0,'مفتوح'],[100000,'$100,000'],[500000,'$500,000'],[1000000,'$1,000,000'],[10000000,'$10,000,000']], 'dex:minBuySellRatio':[[0,'لا يهم'],[1,'1.0x'],[1.5,'1.5x'],[2,'2.0x'],[3,'3.0x']], 'dex:allowedDexes':[['raydium','Raydium فقط'],['raydium_orca','Raydium + Orca'],['raydium_orca_meteora','Raydium + Orca + Meteora'],['all','كل DEX']], 'dex:antiDuplicate':[[true,'مفعّل'],[false,'معطّل']] };
const watcher = new DexWatcher({ settings: settings(), onError: (e) => console.error(`[watcher] ${e.message}`), onFilter: (candidate, reason, stage) => { console.log(`[filter] ${stage}: ${reason} — ${candidate?.symbol || candidate?.mint}`); const s = settings(); s.rejectStats = s.rejectStats || {}; const key = `${stage}: ${reason}`; s.rejectStats[key] = (s.rejectStats[key] || 0) + 1; s.checkedCount = Number(s.checkedCount || 0) + 1; s.lastFilterResult = reason; s.lastCheckAt = new Date().toISOString(); save(s); }, onCandidate: async (candidate) => { const s = settings(); if (s.killSwitch || !s.autoWatcherEnabled || !canTrade(s)) return; const available = Number(s.paperAvailableSol || 0); const allocation = available * Number(s.paperAllocationPct || 5) / 100; if (!Number.isFinite(available) || available < 0.001 || allocation < 0.001) { console.warn(`[trade] تخطي الشراء: الرصيد المتاح غير كافٍ (${available.toFixed(6)} SOL)`); return; } const amount = Math.min(available, allocation); try { const quote = await getQuote({ jupiterUrl: config.jupiterUrl, inputMint: SOL_MINT, outputMint: candidate.mint, amountLamports: Math.floor(amount * 1e9), slippageBps: 100 }); const live = !s.paperTradingEnabled && s.liveTrading; const swap = live ? await executeSwap({ rpcUrl: config.rpcUrl, jupiterUrl: config.jupiterUrl, secret: config.masterPrivateKey, quote, liveTrading: true, priorityFeeMaxLamports: config.priorityFeeMaxLamports }) : null; await openPosition({ adminId: config.adminId, key: config.encryptionKey, jupiterUrl: config.jupiterUrl, mint: candidate.mint, investedSol: amount, quote, metadata: candidate, mode: live ? 'live' : 'paper', buySignature: swap?.signature || null }); if (!live) s.paperAvailableSol = available - amount; s.tradesToday = Number(s.tradesToday || 0) + 1; s.paperEvents = [...(s.paperEvents || []), { type: 'شراء', name: `${candidate.name} (${candidate.symbol})`, mint: candidate.mint, investedSol: amount, tokenAmount: Number(quote.outAmount) / 1e6, unitPrice: amount / (Number(quote.outAmount) / 1e6), liquidityUsd: candidate.liquidityUsd, volumeUsd: candidate.volumeUsd, buyers: candidate.dexBuys, ageSec: candidate.createdAt ? Date.now() / 1000 - candidate.createdAt : null, feeSol: swap?.feeSol || 0, signature: swap?.signature || null, timestamp: Date.now() }].slice(-50); await save(s); } catch (e) { console.error(`[trade] ${e.message}`); } } });
const refreshOpenSymbols = () => { try { watcher.openSymbolsCache = getPositions(config.adminId, config.encryptionKey).filter((p) => p.status === 'open').map((p) => String(p.symbol || '').trim().toUpperCase()).filter(Boolean); } catch (_) {} }; refreshOpenSymbols(); const openSymbolsTimer = setInterval(refreshOpenSymbols, 60000); openSymbolsTimer.unref();
function canTrade(s) { return Number(s.maxTradesPerDay || 0) <= 0 || Number(s.tradesToday || 0) < Number(s.maxTradesPerDay); }
async function dashboardText(s, live = null, refresh = true) { const all = getPositions(config.adminId, config.encryptionKey); const p = all.filter((x) => x.status === 'open'); const priced = live || (refresh ? await refreshPositionsCached({ adminId: config.adminId, key: config.encryptionKey, jupiterUrl: config.jupiterUrl }) : { values: [] }); const priceValues = (priced?.values || []).filter((x) => Number.isFinite(x.currentSol) && Number.isFinite(x.pnlSol)); const hasPrices = priceValues.length > 0; const byId = new Map(priceValues.map((x) => [x.id, x])); const investedSol = p.reduce((sum, x) => sum + Number(x.investedSol || 0), 0); const currentValueSol = hasPrices ? p.reduce((sum, x) => sum + Number(byId.get(x.id)?.currentSol || 0), 0) : null; const floatingPnl = hasPrices ? p.reduce((sum, x) => sum + Number(byId.get(x.id)?.pnlSol || 0), 0) : null; const realizedPnl = Number(s.paperPnlSol || 0) + all.reduce((sum, x) => sum + Number(x.realizedPnlSol || 0), 0); const realizedProfit = Math.max(0, realizedPnl); const realizedLoss = Math.min(0, realizedPnl); const floatingProfit = Math.max(0, floatingPnl || 0); const floatingLoss = Math.min(0, floatingPnl || 0); const st = watcher.status(); const rej = Object.entries(st.rejectStats || {}).slice(-3).map(([k,v])=>`• ${k}: ${v}`).join('\n') || '• لا توجد'; return `📊 لوحة القنص — DEX\n⚡ الحالة: ${st.running ? 'يعمل' : 'متوقف'}\n💰 الرصيد المتاح: ${Number(s.paperAvailableSol || 0).toFixed(4)} SOL\n📦 المستثمر في المراكز: ${investedSol.toFixed(6)} SOL\n💎 القيمة الحالية للمراكز: ${currentValueSol == null ? 'قيد التحديث' : currentValueSol.toFixed(6) + ' SOL'}\n📈 المراكز المفتوحة: ${p.length}\n✅ الربح المحقق: +${realizedProfit.toFixed(6)} SOL\n❌ الخسارة المحققة: ${realizedLoss.toFixed(6)} SOL\n🟢 الربح الحالي: ${floatingPnl == null ? 'قيد التحديث' : '+' + floatingProfit.toFixed(6) + ' SOL'}\n🔻 الخسارة الحالية: ${floatingPnl == null ? 'قيد التحديث' : floatingLoss.toFixed(6) + ' SOL'}\n🎯 الطبقات: DexPaprika [مفعّل] | GoPlus [${yesNo(s.goplus.enabled)}] | Solana Tracker [${yesNo(s.tracker.enabled)}]\n📡 الفحص: ${st.checked} عملة | آخر فحص: ${st.lastPollAt ? new Date(st.lastPollAt).toLocaleTimeString('ar-IQ') : '—'}\n🛡️ الوضع: ${s.paperTradingEnabled ? 'Paper' : 'Live'}\n🔍 فلاتر تكرار: ${s.dex.antiDuplicate !== false ? 'مفعّل' : 'معطّل'}\n📊 إحصاء: فُحص ${st.checked} | اجتاز ${st.passCount || 0} | رُفض ${st.rejectCount || 0}\n\n❌ أسباب الرفض:\n${rej}`; }
async function show(ctx, text, keyboard) { if (ctx.callbackQuery?.data && !['home', 'dashboard', 'watch:on', 'watch:off'].includes(ctx.callbackQuery.data)) dashboardMessages.delete(String(ctx.chat?.id)); try { return await ctx.editMessageText(text, { reply_markup: keyboard }); } catch (_) { return await ctx.reply(text, { reply_markup: keyboard }); } }
const dashboardMessages = new Map();
function rememberDashboard(ctx, message) { const chatId = ctx.chat?.id; const messageId = ctx.callbackQuery?.message?.message_id || message?.message_id; if (chatId && messageId) dashboardMessages.set(String(chatId), { chatId, messageId }); }
async function renderDashboard(ctx) { const s = settings(); const message = await show(ctx, await dashboardText(s, null, false), mainKeyboard(s)); rememberDashboard(ctx, message); }
async function refreshDashboardMessages() { if (!dashboardMessages.size) return; const s = settings(); let live; try { live = await refreshPositionsCached({ adminId: config.adminId, key: config.encryptionKey, jupiterUrl: config.jupiterUrl }); } catch (_) { return; } const text = await dashboardText(s, live); for (const [key, target] of dashboardMessages) { try { await bot.api.editMessageText(target.chatId, target.messageId, text, { reply_markup: mainKeyboard(s) }); } catch (error) { if (error.error_code === 400 && /message is not modified|message to edit not found/i.test(error.description || '')) { if (/not found/i.test(error.description || '')) dashboardMessages.delete(key); } } } }
const dashboardRefreshTimer = setInterval(() => refreshDashboardMessages().catch((error) => console.error(`[dashboard-refresh] ${error.message}`)), 15000); dashboardRefreshTimer.unref();
async function walletAddress() { return keypairFromSecret(config.masterPrivateKey).publicKey.toBase58(); }
async function solUsd() { try { const axios = require('axios'); const { data } = await axios.get('https://api.coingecko.com/api/v3/simple/price', { params: { ids: 'solana', vs_currencies: 'usd' }, timeout: 5000 }); return Number(data?.solana?.usd || 0); } catch (_) { return 0; } }
async function sellOne(position) { const s = settings(); const result = await closePosition({ adminId: config.adminId, key: config.encryptionKey, positionId: position.id, fraction: 1, jupiterUrl: config.jupiterUrl, rpcUrl: config.rpcUrl, ownerSecret: config.masterPrivateKey }); if (result) { const received = Number(result.currentSol || 0); s.paperAvailableSol = Number(s.paperAvailableSol || 0) + received; s.paperEvents = [...(s.paperEvents || []), { type: 'بيع', name: position.name, mint: position.mint, reason: 'Manual', receivedSol: received, pnlSol: result.pnlSol, pnlPct: result.pnlPct, feeSol: result.feeSol || 0, signature: result.signature || null, durationMin: (Date.now() - position.openedAt) / 60000, timestamp: Date.now() }].slice(-50); await save(s); } return result; }
bot.command(['start','menu'], async (ctx) => renderDashboard(ctx));
bot.callbackQuery('home', async (ctx) => { await safeAnswer(ctx); await renderDashboard(ctx); });
bot.callbackQuery('dashboard', async (ctx) => { await safeAnswer(ctx); await renderDashboard(ctx); });
bot.callbackQuery('watch:on', async (ctx) => { await safeAnswer(ctx, 'تم التشغيل'); if (!isAdmin(ctx)) return; const s = settings(); s.autoWatcherEnabled = true; s.killSwitch = false; await save(s); watcher.updateSettings(s); watcher.start(); console.log(`[watcher] enabled; status=${JSON.stringify(watcher.status())}`); await renderDashboard(ctx); });
bot.callbackQuery('watch:off', async (ctx) => { await safeAnswer(ctx, 'تم الإيقاف'); if (!isAdmin(ctx)) return; const s = settings(); s.autoWatcherEnabled = false; await save(s); watcher.stop(); await renderDashboard(ctx); });
bot.callbackQuery('settings', async (ctx) => { await safeAnswer(ctx); await show(ctx, '⚙️ الإعدادات', settingsKeyboard(settings())); });
bot.callbackQuery('filters', async (ctx) => { await safeAnswer(ctx); await show(ctx, '⚙️ فلاتر الحماية', filtersKeyboard(settings())); });
for (const section of ['dex','goplus','tracker','risk']) bot.callbackQuery(`filters:${section}`, async (ctx) => { await safeAnswer(ctx); await show(ctx, section === 'dex' ? '📊 فلاتر DexPaprika' : section === 'goplus' ? '🛡️ فلاتر GoPlus' : section === 'tracker' ? '🛡️ فلاتر Solana Tracker' : '🛑 إدارة المخاطر', screen(section, settings())); });
bot.callbackQuery('wallet', async (ctx) => { await safeAnswer(ctx); const address = await walletAddress(); await show(ctx, `💼 محفظتك\nالعنوان: ${short(address)}`, new InlineKeyboard().copyText('📋 نسخ العنوان', address).row().text('💰 عرض الرصيد', 'wallet:balance').row().text('🪙 العملات غير المباعة', 'unsold').row().text('🔙 رجوع', 'home')); });
bot.callbackQuery('wallet:balance', async (ctx) => { await safeAnswer(ctx); try { const address = await walletAddress(); const sol = await getSolBalance({ rpcUrl: config.rpcUrl, owner: address }); const usd = await solUsd(); await show(ctx, `💰 رصيد المحفظة\nSOL: ${sol.toFixed(4)}\nUSD: $${(sol * usd).toFixed(2)}`, new InlineKeyboard().text('🔄 تحديث', 'wallet:balance').row().text('🔙 رجوع', 'wallet')); } catch (e) { await show(ctx, `تعذر قراءة الرصيد: ${e.message}`, new InlineKeyboard().text('🔄 إعادة المحاولة', 'wallet:balance').row().text('🔙 رجوع', 'wallet')); } });
bot.callbackQuery('unsold', async (ctx) => { await safeAnswer(ctx); const positions = getPositions(config.adminId, config.encryptionKey).filter((p) => p.status === 'open'); const uniqueMints = new Set(positions.map((p) => p.mint)).size; const k = new InlineKeyboard(); for (const p of positions) { const ref = String(p.id).split(':').pop(); const label = (p.symbol || p.name || 'TOKEN').slice(0, 8); k.copyText(`📋 ${label} [${short(p.mint)}]`, p.mint).row().text('📊 السعر الحالي', `position:price:${ref}`).text('💰 بيع بسعر السوق', `position:sell:${ref}`).row(); } k.text('🔙 رجوع', 'wallet'); await show(ctx, `🪙 العملات غير المباعة (${uniqueMints} عملة)\n${positions.length ? 'اختر عملية:' : 'لا توجد عملات غير مباعة.'}`, k); });
bot.callbackQuery(/^position:sell:(.+)$/, async (ctx) => { await safeAnswer(ctx); if (!isAdmin(ctx)) return; const p = getPositions(config.adminId, config.encryptionKey).find((x) => String(x.id).endsWith(`:${ctx.match[1]}`) && x.status === 'open'); if (!p) return show(ctx, 'المركز غير موجود.', new InlineKeyboard().text('🔙 رجوع', 'unsold')); try { const result = await sellOne(p); await show(ctx, `✅ تم البيع بسعر السوق\n${p.name} (${p.symbol})\nالربح/الخسارة: ${Number(result?.pnlSol || 0).toFixed(6)} SOL (${Number(result?.pnlPct || 0).toFixed(2)}%)`, new InlineKeyboard().text('🪙 العملات غير المباعة', 'unsold').row().text('🔙 العملات غير المباعة', 'unsold')); } catch (e) { await show(ctx, `❌ تعذر البيع: ${e.message}`, new InlineKeyboard().text('🔙 رجوع', 'unsold')); } });
bot.callbackQuery(/^position:price:(.+)$/, async (ctx) => { await safeAnswer(ctx); const p = getPositions(config.adminId, config.encryptionKey).find((x) => String(x.id).endsWith(`:${ctx.match[1]}`) && x.status === 'open'); if (!p) return; try { const q = await getQuote({ jupiterUrl: config.jupiterUrl, inputMint: p.mint, outputMint: SOL_MINT, amountLamports: p.tokenAmountRaw, slippageBps: 100 }); await ctx.reply(`📊 السعر الحالي لـ ${p.symbol || p.name}: ${(Number(q.outAmount) / 1e9).toFixed(6)} SOL`); } catch (e) { await ctx.reply(`تعذر جلب السعر: ${e.message}`); } });
bot.callbackQuery('cfg:allocation', async (ctx) => { await safeAnswer(ctx); const k = new InlineKeyboard(); for (const v of [1,2,3,4,5,10,15,25,30,35,40,50,60,75,90,100]) k.text(`${v}%`, `cfg:set:allocation:${v}`).row(); await show(ctx, '💰 حجم الصفقة (نسبة من رأس المال)', k); });
bot.callbackQuery('cfg:trades', async (ctx) => { await safeAnswer(ctx); const k = new InlineKeyboard(); for (const v of [1,2,3,4,5,10]) k.text(String(v), `cfg:set:trades:${v}`); k.text('غير محدود', 'cfg:set:trades:0').row(); k.text('🔙 رجوع', 'settings'); await show(ctx, '🔢 عدد الصفقات اليومي', k); });
bot.callbackQuery('cfg:profit', async (ctx) => { await safeAnswer(ctx); const k = new InlineKeyboard(); for (const v of [5,10,15,25,35,50,75,100]) k.text(`${v}%`, `cfg:set:profit:${v}`).row(); await show(ctx, '🎯 جني الأرباح', k); });
bot.callbackQuery('cfg:stop', async (ctx) => { await safeAnswer(ctx); const k = new InlineKeyboard(); for (const v of [5,10,15,20,25,30]) k.text(`-${v}%`, `cfg:set:stop:${v}`); await show(ctx, '🛑 وقف الخسارة', k); });
bot.callbackQuery(/^cfg:set:(allocation|trades|profit|stop):([0-9]+)$/, async (ctx) => { await safeAnswer(ctx, 'تم الحفظ'); const type = ctx.match[1]; const value = Number(ctx.match[2]); const s = settings(); if (type === 'allocation') s.paperAllocationPct = value; if (type === 'trades') s.maxTradesPerDay = value; if (type === 'profit') s.paperTakeProfitFirstPct = value; if (type === 'stop') s.paperStopLossPct = value; await save(s); watcher.updateSettings(s); if (type === 'allocation') return show(ctx, `✅ حجم الصفقة: ${value}%\n\n🔢 عدد الصفقات اليومي`, new InlineKeyboard().text('فتح عدد الصفقات', 'cfg:trades').row().text('🔙 الإعدادات', 'settings')); if (type === 'trades') return show(ctx, `✅ عدد الصفقات: ${value || 'غير محدود'}\n\n🎯 جني الأرباح`, new InlineKeyboard().text('فتح جني الأرباح', 'cfg:profit').row().text('🔙 الإعدادات', 'settings')); await show(ctx, `✅ ${type === 'profit' ? 'جني الأرباح: +' + value + '%' : 'وقف الخسارة: -' + value + '%'}`, settingsKeyboard(s)); });
for (const [id, field] of [['cfg:buy','paperTradingEnabled'],['cfg:sell','autoSellEnabled']]) bot.callbackQuery(id, async (ctx) => { await safeAnswer(ctx, 'تم التحديث'); const s = settings(); s[field] = !s[field]; await save(s); watcher.updateSettings(s); await show(ctx, '⚙️ الإعدادات', settingsKeyboard(s)); });
bot.callbackQuery('reset:ask', async (ctx) => { await safeAnswer(ctx); const s = settings(); const message = s.paperTradingEnabled ? '⚠️ سيتم حذف مراكز Paper وإحصائيات الفحص وسجل العمليات. هل أنت متأكد؟' : '⚠️ سيتم تنظيف إحصائيات اللوحة فقط. مراكز Live والعملات الموجودة في المحفظة لن تتغير. هل أنت متأكد؟'; await show(ctx, message, new InlineKeyboard().text('✅ تأكيد', 'reset:do').row().text('🔙 إلغاء', 'home')); });
bot.callbackQuery('reset:do', async (ctx) => { await safeAnswer(ctx); const s = settings(); watcher.stop(); if (s.paperTradingEnabled) { const positions = getPositions(config.adminId, config.encryptionKey); const livePositions = positions.filter((p) => p.mode === 'live'); await replacePositions(config.adminId, livePositions, config.encryptionKey); s.paperAvailableSol = s.paperCapitalSol; s.paperPnlSol = 0; s.paperEvents = []; } s.checkedCount = 0; s.rejectStats = {}; s.lastCheckAt = null; s.lastMint = null; s.tradesToday = 0; await save(s); watcher.reset(); watcher.updateSettings(s); if (s.autoWatcherEnabled && !s.killSwitch) watcher.start(); await show(ctx, s.paperTradingEnabled ? '✅ تم حذف جميع مراكز Paper نهائياً وبدأت دورة جديدة من الصفر.' : '✅ تم تنظيف لوحة Live فقط. المراكز والعملات الحقيقية محفوظة.', mainKeyboard(s)); });
bot.callbackQuery('mode:toggle', async (ctx) => { await safeAnswer(ctx); const s = settings(); if (s.paperTradingEnabled) { let balance = 'غير متاح'; try { balance = (await getSolBalance({ rpcUrl: config.rpcUrl, owner: await walletAddress() })).toFixed(4); } catch (_) {} await show(ctx, `⚠️ سيتم التداول بأموال حقيقية!\nالرصيد الحقيقي: ${balance} SOL\nهل أنت متأكد؟`, new InlineKeyboard().text('✅ تأكيد', 'mode:live').row().text('🔙 إلغاء', 'home')); } else await show(ctx, '🧪 سيتم التبديل إلى المحاكاة. لن تُنفذ معاملات حقيقية.', new InlineKeyboard().text('✅ تأكيد', 'mode:paper').row().text('🔙 إلغاء', 'home')); });
bot.callbackQuery('mode:live', async (ctx) => { await safeAnswer(ctx); const s = settings(); s.paperTradingEnabled = false; s.liveTrading = true; await save(s); await show(ctx, '✅ تم تفعيل التداول الحقيقي.', mainKeyboard(s)); });
bot.callbackQuery('mode:paper', async (ctx) => { await safeAnswer(ctx); const s = settings(); s.paperTradingEnabled = true; s.liveTrading = false; await save(s); await show(ctx, '✅ تم تفعيل التداول الوهمي.', mainKeyboard(s)); });
bot.callbackQuery(/^choose:(dex|goplus|tracker|risk):(.+)$/, async (ctx) => { await safeAnswer(ctx); const section = ctx.match[1]; const key = ctx.match[2]; const options = choices[`${section}:${key}`] || [[true,'مفعّل'],[false,'معطّل']]; const k = new InlineKeyboard(); for (const [value,label] of options) k.text(label, `set:${section}:${key}:${String(value)}`).row(); k.text('🔙 إلغاء', `filters:${section}`); await show(ctx, `اختر قيمة ${key}:`, k); });
bot.callbackQuery(/^set:(dex|goplus|tracker|risk):([^:]+):(.+)$/, async (ctx) => { await safeAnswer(ctx, 'تم الحفظ'); const [,section,key,raw] = ctx.match; const s = settings(); s[section][key] = raw === 'true' ? true : raw === 'false' ? false : Number.isNaN(Number(raw)) ? raw : Number(raw); await save(s); watcher.updateSettings(s); await show(ctx, section === 'dex' ? '📊 فلاتر DexPaprika' : section === 'goplus' ? '🛡️ فلاتر GoPlus' : section === 'tracker' ? '🛡️ فلاتر Solana Tracker' : '🛑 إدارة المخاطر', screen(section, s)); });
bot.catch((e) => console.error(`[telegram] ${e.message || e}`));
const boot = settings();
if (process.env.AUTO_START_WATCHER !== 'false' && !boot.killSwitch) boot.autoWatcherEnabled = true;
watcher.updateSettings(boot);
if (boot.autoWatcherEnabled && !boot.killSwitch) { save(boot); watcher.start(); console.log(`[watcher] auto-started on boot; status=${JSON.stringify(watcher.status())}`); }
module.exports = bot; module.exports.startWatcher = () => { const s = settings(); s.autoWatcherEnabled = true; save(s); watcher.updateSettings(s); return watcher.start(); }; module.exports.watcher = watcher;
